---
- name: Standardize interface description and VLAN
  hosts: all
  gather_facts: no
  vars:
    iface: "GigabitEthernet1"
    desc: "Managed by Ansible Training"
    vlan_id: 123
  tasks:
    - name: Set interface description (Cisco IOS)
      when: ansible_network_os == 'cisco.ios.ios'
      cisco.ios.ios_interface:
        name: "{{ iface }}"
        description: "{{ desc }}"
        state: present

    - name: Ensure VLAN present (Cisco IOS)
      when: ansible_network_os == 'cisco.ios.ios'
      cisco.ios.ios_vlans:
        config:
          - vlan_id: "{{ vlan_id }}"
            name: "TRAINING_VLAN"
        state: merged

    - name: Set interface description (Juniper Junos)
      when: ansible_network_os == 'junipernetworks.junos.junos'
      junipernetworks.junos.junos_interface:
        name: "ge-0/0/0"
        description: "{{ desc }}"
        state: present
